### ISSUE TITLE
Issues with running multivariate PLS-DA analysis on my dataset on galaxy

### ISSUE THREAD

**Issue by Justin1609** [workflow4metabolomics/multivariate#12]
Hi there @ethevenot 

Sorry to bother you, but I have now tried everything to get my data in the correct format for it to work for workflow4metabolomics.org that uses galaxy server. I have checked my data several times to ensure it is exactly the same as the example, but I just keep getting errors. My files are now in TSV file format but when I hit "execute" I get the following error:

Error in read.table(argVc["variableMetadata_in"], check.names = FALSE,  : 
  duplicate 'row.names' are not allowed

Please I urgently need to get this analysis done on my data set, any help would be greatly appreciated.

I have attached my files in CSV format, as gitHub doesn't allow me to upload TSV files, for reference so that you can see if there is any errors that may be causing the issues.

Kind regards

[S_cerevisiae_dataMatrix.csv](https://github.com/workflow4metabolomics/multivariate/files/7677265/S_cerevisiae_dataMatrix.csv)
[S_cerevisiae_sampleMetadata.csv](https://github.com/workflow4metabolomics/multivariate/files/7677266/S_cerevisiae_sampleMetadata.csv)
[S_cerevisiae_variablemetaData.csv](https://github.com/workflow4metabolomics/multivariate/files/7677268/S_cerevisiae_variablemetaData.csv)

J

**Comment by ethevenot** [comment]
Hi,
Would you please send me your .tsv files and R code at etienne.thevenot@cea.fr
Best,
Etienne.

**Comment by Justin1609** [comment]
Hi @ethevenot 

I don't have code for the ropls analysis as I was using Galaxy interface for that, but I will send through the TSV files that I created. I am very new to using R and therefore I though that making use of Galaxy would be easier in this case.

Kind regards

J

**Comment by Justin1609** [comment]
Morning Etienne

Sorry to bother you, I am just checking to make sure that you received my
email yesterday with the data files? Thank you again for the help, I truly
appreciate it.

Kind regards

Justin

**Comment by ethevenot** [comment]
Hi Justin,
There are two problems in the files:
1) your dataMatrix should be transposed (i.e. variables as rows)
2) the order of your variables in the dataMatrix and variableMetadata are different ; for this latter issue, it may be corrected automatically by using the checkFormat tool on Workflow4Metabolomics (provided that issue 1 has been addressed)
Best,
Etienne.
